core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index")
]

forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path("", views.CategoriesView.as_view(),
         name="categories"),
    path("category/create", views.CategoryCreate.as_view(),
         name="category_create"),
    path("category/delete/<int:pk>", views.CategoryDelete.as_view(),
         name="category_delete"),

    path("themes/<int:category_pk>", views.ThemesView.as_view(),
         name="themes"),
    path("theme/<int:pk>", views.ThemeMessagesView.as_view(),
         name="theme"),
    path("theme/create/<int:category_pk>", views.ThemeCreate.as_view(),
         name="theme_create"),
    path("theme/delete/<int:category_pk>/<int:pk>",
         views.ThemeDelete.as_view(),
         name="theme_delete"),

    path("message/create/", views.ThemeMessageCreate.as_view(),
         name="create_message"),
    path("message/delete/<int:theme_pk>/<int:pk>",
         views.ThemeMessageDelete.as_view(),
         name="delete_message"),
]

profiles/urls.py
from django.urls import path

from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('profile/<int:pk>', views.ProfileDetail.as_view(), name="profile"),
    path('update/<int:pk>', views.ProfileUpdate.as_view(), name="update"),
    path('delete/<int:pk>', views.ProfileDelete.as_view(), name="delete"),

    path('password/change/<int:pk>', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('registration/', views.RegisterView.as_view(), name="registration"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('forum/', include('forum.urls', namespace='forum')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


def get_pic_url(self, filename):
    return f"images/profiles/{self.pk}/profile_pic/{filename}"


class Profile(AbstractUser):
    profile_pic = models.ImageField("аватар профиля",
                                    upload_to=get_pic_url,
                                    default="defaults/images/noimage.png")

    description = models.TextField("обо мне")

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"

    def __str__(self):
        return f"Профиль {self.username}"

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from profiles import models


class NoInitialValueFileInput(forms.ClearableFileInput):
    def is_initial(self, value):
        return False


class ProfileUpdate(UserChangeForm):
    password = None
    profile_pic = forms.ImageField(initial=None,
                                   label="Аватар профиля",
                                   widget=NoInitialValueFileInput)
    description = forms.CharField(label="Обо мне",
                                  widget=forms.Textarea,
                                  required=False)

    class Meta:
        model = models.Profile
        fields = ("username", "profile_pic", "description")


class ProfileCreate(UserCreationForm):
    class Meta:
        model = models.Profile
        fields = ("username", "password1", "password2")

profiles/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView as LoginViewDjango, \
    PasswordChangeView
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

import utils
from forum import models as forum_models
from mixins import LoginRequiredMixin, AuthMenuMixin
from profiles import models, forms


class ProfileDetail(AuthMenuMixin, DetailView):
    model = models.Profile
    template_name = "profiles/profile.html"
    extra_context = {"title": "Профиль"}

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.get_object()
        context["latest_messages"] = forum_models.ThemeMessage.objects.filter(
            from_user__pk=user.pk).order_by("-created_at")[:3]
        context["is_same_user"] = utils.is_same_user(self.request.user, user)
        return context


class ProfileUpdate(AuthMenuMixin, LoginRequiredMixin,
                    UpdateView):
    model = models.Profile
    form_class = forms.ProfileUpdate
    template_name = "profiles/update.html"
    extra_context = {"title": "Редактирование профиля"}

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not utils.is_same_user(request.user, obj.pk):
            raise PermissionDenied()
        return super().dispatch(request, args=args, kwargs=kwargs)

    def get_success_url(self):
        return reverse("profiles:profile",
                       kwargs={"pk": self.request.user.pk})


class ProfileDelete(AuthMenuMixin, LoginRequiredMixin,
                    DeleteView):
    model = models.Profile
    template_name = "profiles/delete.html"
    extra_context = {"title": "Удаление профиля"}

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not utils.is_same_user(request.user, obj.pk):
            raise PermissionDenied()
        return super().dispatch(request, args=args, kwargs=kwargs)

    def get_success_url(self):
        return reverse("core:index")


class ChangePasswordView(AuthMenuMixin, LoginRequiredMixin,
                         PasswordChangeView):
    extra_context = {"title": "Смена пароля"}
    template_name = "profiles/change_password.html"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not utils.is_same_user(request.user, obj.pk):
            raise PermissionDenied()
        self.object = obj
        return super().dispatch(request, args=args, kwargs=kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(kwargs=kwargs)
        context["object"] = self.object
        return context

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(models.Profile, pk=pk)

    def get_success_url(self):
        return reverse("profiles:profile",
                       kwargs={"pk": self.request.user.pk})


class RegisterView(AuthMenuMixin, CreateView):
    model = models.Profile
    form_class = forms.ProfileCreate
    template_name = "profiles/registration.html"
    success_url = reverse_lazy("profiles:login")
    extra_context = {"title": "Регистрация"}


class LoginView(AuthMenuMixin, LoginViewDjango):
    template_name = "profiles/login.html"
    extra_context = {"title": "Вход"}

    def get_success_url(self):
        return reverse("core:index")


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect(reverse("core:index"))

templates/profiles/change_password.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Смена пароля</div>
<form class="m-3" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-danger">Сменить пароль</button>
    <a href="{% url 'profiles:profile' object.pk %}" class="btn btn-primary">Отмена</a>
</form>
{% endblock content %}

templates/profiles/delete.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Удаление профиля</div>
<form class="m-3" method="post">
    {% csrf_token %}
    {{ form }}
    <p>Удалить профиль {{ object.name }}?</p>
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'profiles:profile' object.pk %}" class="btn btn-primary">Отмена</a>
</form>
{% endblock content %}

templates/profiles/login.html
{% extends 'base/base.html' %}
{% block content %}
<form class="m-3" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">Войти</button>
</form>
{% endblock content %}

templates/profiles/profile.html
{% extends 'base/base.html' %}
{% block content %}
<div class="card d-flex flex-row m-3">
    <div style="height:100px; width:100px;overflow:hidden;" class="col-md-2 m-3">
        <img src="{{ object.profile_pic.url }}" class="img-thumbnail">
    </div>
    <div class="card-body d-flex flex-column col-md-10">
        <h5 class="card-title">{{ object.username }}</h5>
        <p class="card-text">{{ object.description }}
        <p>
            {% if latest_messages %}
        <h5 class="card-title">Последние сообщения пользователя</h5>
        {% endif %}
        {% for msg in latest_messages %}
        <div class="card mb-3 mx-auto" style="width: 100%;">
            <a class="link-underline link-underline-opacity-0 text-black flex-grow-1"
               href="{% url 'forum:theme' msg.theme.pk %}">
                <div class="row g-0">
                    <div class="col-md-2 m-2" style="height:100px; width:100px;overflow:hidden;">
                        <img src="{{msg.from_user.profile_pic.url}}"
                             class="img-thumbnail rounded-start mx-auto flex-grow-1">
                    </div>
                    <div class="col-md-10">
                        <div class="card-body">
                            <h5 class="card-title">{{msg.from_user.username }}</h5>

                            <p class="card-text">{{ msg.text }}</p>
                            <p class="card-text"><small class="text-body-secondary">{{ msg.created_at }}</small></p>
                            <p class="card-text"><small class="text-body-secondary">Из темы {{ msg.theme.name }}</small>
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% empty %}
        <p class="card-text">Пользователь не отправлял сообщения</p>
        {% endfor %}
        {% if is_same_user %}
        <div class="d-flex gap-3">
            <a href="{% url 'profiles:update' object.pk %}" class="btn btn-primary">Обновить профиль</a>
            <a href="{% url 'profiles:change_password' object.pk %}" class="btn btn-primary">Обновить пароль</a>
            <a href="{% url 'profiles:delete' object.pk %}" class="btn btn-danger">Удалить профиль</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/profiles/registration.html
{% extends 'base/base.html' %}
{% block content %}
<form class="m-3" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">Войти</button>
</form>
{% endblock content %}

templates/profiles/update.html
{% extends 'base/base.html' %}
{% block content %}
<form class="m-3" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <p>{{ form.username.label_tag }} {{form.username}}</p>
    <p>{{ form.description.label_tag }} {{form.description}}</p>
    <p>{{ form.profile_pic.label_tag }} {{form.profile_pic}}</p>
    <button type="submit" class="btn btn-success">Обновить</button>
</form>
{% endblock content %}