core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index")
]

forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path("", views.CategoriesView.as_view(),
         name="categories"),
    path("category/create", views.CategoryCreate.as_view(),
         name="category_create"),
    path("category/delete/<int:pk>", views.CategoryDelete.as_view(),
         name="category_delete"),

    path("themes/<int:category_pk>", views.ThemesView.as_view(),
         name="themes"),
    path("theme/<int:pk>", views.ThemeMessagesView.as_view(),
         name="theme"),
    path("theme/create/<int:category_pk>", views.ThemeCreate.as_view(),
         name="theme_create"),
    path("theme/delete/<int:category_pk>/<int:pk>",
         views.ThemeDelete.as_view(),
         name="theme_delete"),

    path("message/create/", views.ThemeMessageCreate.as_view(),
         name="create_message"),
    path("message/delete/<int:theme_pk>/<int:pk>",
         views.ThemeMessageDelete.as_view(),
         name="delete_message"),
]

profiles/urls.py
from django.urls import path

from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('profile/<int:pk>', views.ProfileDetail.as_view(), name="profile"),
    path('update/<int:pk>', views.ProfileUpdate.as_view(), name="update"),
    path('delete/<int:pk>', views.ProfileDelete.as_view(), name="delete"),

    path('password/change/<int:pk>', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('registration/', views.RegisterView.as_view(), name="registration"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('forum/', include('forum.urls', namespace='forum')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

forum/models.py
from django.conf import settings
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField("название категории", max_length=255)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}:{self.created_at}:{self.changed_at}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ("created_at",)


class Theme(models.Model):
    name = models.CharField("название темы", max_length=255)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name="themes")
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.category}:{self.name}"

    class Meta:
        verbose_name = "тема"
        verbose_name_plural = "темы"
        ordering = ("created_at",)


class Message(models.Model):
    text = models.TextField("текст сообщения")
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.from_user.name}: {self.text}"

    class Meta:
        abstract = True
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"
        ordering = ("created_at",)


class ThemeMessage(Message):
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE,
                              related_name="messages")

forum/forms.py
from django import forms

from forum import models


class ThemeMessageForm(forms.Form):
    text = forms.CharField(label="Сообщение", widget=forms.Textarea)
    theme_pk = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = models.ThemeMessage
        fields = ("text",)

forum/views.py
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView

import utils
from forum import models, forms
from mixins import AuthMenuMixin, StaffOnlyMixin, \
    LoginRequiredMixin


# Create your views here.
class CategoriesView(AuthMenuMixin, ListView):
    model = models.Category
    template_name = "forum/categories.html"
    extra_context = {"title": "Категории"}

    def get_queryset(self):
        return self.model.objects.annotate(
            themes_count=Count("themes"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(kwargs=kwargs)
        context["user"] = self.request.user
        return context


class CategoryCreate(StaffOnlyMixin, LoginRequiredMixin,
                     AuthMenuMixin, CreateView):
    model = models.Category
    template_name = "forum/category_create.html"
    fields = ("name",)
    success_url = reverse_lazy("forum:categories")
    extra_context = {"title": "Создание категории"}

    def post(self, request, *args, **kwargs):
        category_name = request.POST.get("name")
        self.model.objects.create(creator_id=self.request.user.pk,
                                  name=category_name)
        return redirect(reverse("forum:categories"))


class CategoryDelete(StaffOnlyMixin, LoginRequiredMixin,
                     AuthMenuMixin, DeleteView):
    model = models.Category
    template_name = "forum/category_delete.html"
    success_url = reverse_lazy("forum:categories")
    extra_context = {"title": "Удаление категории"}


class ThemesView(AuthMenuMixin, ListView):
    model = models.Theme
    template_name = "forum/themes.html"

    def get_queryset(self):
        pk = self.kwargs.get("category_pk")
        return self.model.objects.filter(category__pk=pk).annotate(
            msg_count=Count("messages"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(kwargs=kwargs)

        category = get_object_or_404(
            models.Category,
            pk=self.kwargs.get("category_pk"))
        context["category"] = category
        context["title"] = f"Категория {category.name}"

        context["user"] = self.request.user
        return context


class ThemeCreate(LoginRequiredMixin, AuthMenuMixin,
                  CreateView):
    model = models.Theme
    template_name = "forum/theme_create.html"
    fields = ("name",)
    extra_context = {"title": "Создание темы"}

    def get_success_url(self):
        return reverse("forum:themes",
                       kwargs={"pk": self.kwargs.get("category_pk")})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(kwargs=kwargs)
        context["category_pk"] = self.kwargs.get("category_pk")
        return context

    def post(self, request, *args, **kwargs):
        category_pk = self.kwargs.get("category_pk")
        theme_name = request.POST.get("name")
        self.model.objects.create(category_id=category_pk,
                                  creator_id=self.request.user.pk,
                                  name=theme_name)
        return redirect(reverse("forum:themes",
                                kwargs={"category_pk": category_pk}))


class ThemeDelete(LoginRequiredMixin, AuthMenuMixin,
                  DeleteView):
    model = models.Theme
    template_name = "forum/theme_delete.html"
    extra_context = {"title": "Удаление темы"}

    def dispatch(self, request, *args, **kwargs):
        creator = get_object_or_404(models.Theme,
                                    pk=self.kwargs.get("pk")).creator
        is_same_user = utils.is_same_user(request.user, creator)
        if not (self.request.user.is_staff or is_same_user):
            return utils.handle_no_permission(
                reverse("forum:themes",
                        kwargs={"category_pk": self.kwargs.get("category_pk")
                                }))
        return super().dispatch(request, args=args, kwargs=kwargs)

    def get_success_url(self):
        return reverse("forum:themes",
                       kwargs={"category_pk": self.kwargs.get("category_pk")})


class ThemeMessagesView(AuthMenuMixin, ListView):
    paginate_by = 4
    model = models.ThemeMessage
    template_name = "forum/theme.html"

    def get_queryset(self):
        pk = self.kwargs.get("pk")
        return self.model.objects.filter(theme__pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(kwargs=kwargs)

        theme = get_object_or_404(models.Theme,
                                  pk=self.kwargs.get("pk"))
        context["theme"] = theme
        context["title"] = f"Тема {theme.name}"

        context["is_staff"] = self.request.user.is_staff
        context["user"] = self.request.user

        context["form"] = forms.ThemeMessageForm(
            initial={"theme_pk": theme.pk})
        return context


class ThemeMessageCreate(LoginRequiredMixin, View):
    def post(self,
             request,
             *args,
             **kwargs):
        text = request.POST.get("text")
        theme_pk = int(request.POST.get("theme_pk"))
        models.ThemeMessage.objects.create(
            theme_id=theme_pk, text=text, from_user_id=self.request.user.pk)
        return redirect(
            f'{reverse("forum:theme", kwargs={"pk": theme_pk})}'
            f'?page=last')


class ThemeMessageDelete(LoginRequiredMixin, AuthMenuMixin,
                         DeleteView):
    model = models.ThemeMessage
    template_name = "forum/msg_delete.html"
    extra_context = {"title": "Удаление сообщения"}

    def dispatch(self, request, *args, **kwargs):
        from_user = self.get_object().from_user
        is_same_user = utils.is_same_user(request.user, from_user)

        if not (self.request.user.is_staff or is_same_user):
            raise PermissionDenied()

        return super().dispatch(request, args=args, kwargs=kwargs)

    def get_success_url(self):
        return reverse("forum:theme",
                       kwargs={
                           "pk": self.kwargs.get("theme_pk")
                       }) + "?page=last"

templates/forum/categories.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Список категорий</div>
<table class="table text-center mt-2">
    <thead class="table-primary">
    <tr>
        <th style="width: 60%;">Название категории</th>
        <th>Создатель</th>
        <th>Количество тем</th>
        <th>Дата создания</th>
        <th>Последнее изменение</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for category in object_list %}
    <tr>
        <td><a class="link-underline text-black" style="word-break: break-all;" href="{% url 'forum:themes' category.pk %}">{{ category.name }}</a></td>
        <td>
            {% if category.creator %}
            <div><a href="{% url 'profiles:profile' category.creator.pk %}" class="link-underline link-underline-opacity-0 text-black">{{ category.creator.username }}</a></div>
            {% else %}
            <div>Нет автора</div>
            {% endif %}
        </td>
        <td>
            <div>{{ category.themes_count }}</div>
        </td>
        <td>
            <div>{{ category.created_at }}</div>
        </td>
        <td>
            <div>{{ category.changed_at }}</div>
        </td>
        {% if user.is_staff %}
        <td>
            <div><a href="{% url 'forum:category_delete' category.pk %}" class="btn btn-danger m-3">Удалить</a></div>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if user.is_staff %}
<a href="{% url 'forum:category_create' %}" class="btn btn-primary m-3">Добавить новую категорию</a>
{% endif %}
{% endblock content %}

templates/forum/category_create.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Создание категории</div>
<form class="form mx-auto d-flex flex-column" method="post" action="{% url 'forum:category_create' %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success m-3">Добавить</button>
</form>
{% endblock content %}

templates/forum/category_delete.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Удаление категории</div>
<form class="m-3" method="post">
    {% csrf_token %}
    {{ form }}
    <p>Удалить категорию {{ object.name }}?</p>
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'forum:categories' %}" class="btn btn-primary">Отмена</a>
</form>
{% endblock content %}

templates/forum/msg_delete.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Удаление сообщения</div>
<form class="m-3" method="post">
    {% csrf_token %}
    {{ form }}
    <p>Удалить сообщение?</p>
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'forum:categories' %}" class="btn btn-primary">Отмена</a>
</form>
{% endblock content %}

templates/forum/theme.html
{% extends 'base/base.html' %}

{% block content %}
<div class="display-4  text-center">Тема {{ theme.name }}</div>
<div class="pagination m-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
            {% if 1 != page_obj.previous_page_number %}
            <a class="page-link d-inline" href="?page=1">&laquo; 1</a>
            {% endif %}
            <a class="page-link d-inline" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}

        <span class="current page-link d-inline text-black">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="page-link d-inline"
               href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            {% if page_obj.paginator.num_pages != page_obj.next_page_number %}
            <a class="page-link d-inline" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }} &raquo;</a>
            {% endif %}
        {% endif %}
    </span>
</div>
{% for message in object_list %}
<div class="card mb-3 mx-auto" style="max-width: 700px;">
    <div class="row g-0">
        <div class="col-md-2 m-2" style="height:100px; width:100px;overflow:hidden;">
            <img src="{{message.from_user.profile_pic.url}}" class="img-thumbnail rounded-start mx-auto flex-grow-1">
        </div>
        <div class="col-md-10">
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-between">
                    <a class="link-underline link-underline-opacity-0 text-black"
                                          href="{% url 'profiles:profile' message.from_user.pk %}">{{ message.from_user.username }}</a>
                    {% if is_staff or message.from_user.pk == user.pk %}
                    <a href="{% url 'forum:delete_message' message.theme.pk message.pk %}" class="btn btn-danger">Удалить сообщение</a>
                    {% endif %}
                </h5>
                <p class="card-text">{{ message.text }}</p>
                <p class="card-text"><small class="text-body-secondary">{{ message.created_at }}</small></p>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="display-4 text-center">Нет сообщений в теме!</div>
{% endfor %}
<div class="mx-auto d-flex">
{% if user.is_authenticated %}
<form class="mx-auto d-flex flex-column" method="post" action="{% url 'forum:create_message' %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success m-3">Отправить</button>
</form>

{% else %}
<a href="{% url 'profiles:login' %}" class="mx-auto text-center">Войдите чтобы отправлять сообщения</a>
{% endif %}
</div>

<div class="pagination m-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
            {% if 1 != page_obj.previous_page_number %}
            <a class="page-link d-inline" href="?page=1">&laquo; 1</a>
            {% endif %}
            <a class="page-link d-inline" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}

        <span class="current page-link d-inline text-black">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="page-link d-inline"
               href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            {% if page_obj.paginator.num_pages != page_obj.next_page_number %}
            <a class="page-link d-inline" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }} &raquo;</a>
            {% endif %}
        {% endif %}
    </span>
</div>
{% endblock content %}

templates/forum/theme_create.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Создание темы</div>
<form class="form mx-auto d-flex flex-column" method="post" action="{% url 'forum:theme_create' category_pk %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success m-3">Добавить</button>
</form>
{% endblock content %}

templates/forum/theme_delete.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4 text-center">Удаление темы</div>
<form class="m-3" method="post">
    {% csrf_token %}
    {{ form }}
    <p>Удалить тему {{ object.name }}?</p>
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'forum:categories' %}" class="btn btn-primary">Отмена</a>
</form>
{% endblock content %}

templates/forum/themes.html
{% extends 'base/base.html' %}
{% block content %}
<div class="display-4  text-center">Категория {{ category.name }}</div>
<table class="table text-center mt-2">
    <thead class="table-primary">
    <tr>
        <th style="width: 60%;">Название темы</th>
        <th>Создатель</th>
        <th>Количество сообщений</th>
        <th>Дата создания</th>
        <th>Последнее изменение</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for theme in object_list %}
    <tr>
        <td><a href="{% url 'forum:theme' theme.pk %}" class="link-underline text-black">{{ theme.name }}</a></td>
        <td>
            {% if theme.creator %}
            <div><a href="{% url 'profiles:profile' theme.creator.pk %}" class="link-underline link-underline-opacity-0 text-black">{{ theme.creator.username }}</a></div>
            {% else %}
            <div>Нет автора</div>
            {% endif %}
        </td>
        <td>
            <div>{{ theme.msg_count }}</div>
        </td>
        <td>
            <div>{{ theme.created_at }}</div>
        </td>
        <td>
            <div>{{ theme.changed_at }}</div>
        </td>
        {% if user.is_staff or theme.creator and theme.creator.pk == user.pk %}
        <td>
            <div><a href="{% url 'forum:theme_delete' category.pk theme.pk %}" class="btn btn-danger m-3">Удалить</a></div>
        </td>
        {% endif %}
    </tr>
    {% empty %}
    <div class="display-4  text-center">В категории нет тем</div>
    {% endfor %}
    </tbody>
</table>
{% if user.is_authenticated %}
<a style="word-break: break-all;" href="{% url 'forum:theme_create' category.pk %}" class="btn btn-primary m-3">Добавить
    новую тему</a>
{% endif %}
{% endblock content %}